### ISSUE TITLE
Error parsing sequence files

### ISSUE THREAD

**Issue by lowkri** [saccharis/SACCHARIS_2#7]
Currently, user sequence fasta files are not being imported correctly. We are actively working on a fix.

Error:
(saccharis) abbottlab@proteus:/media/abbottlab/QNAP-Proteus/kristin/test$ saccharis -c characterized -f GH33 --fresh -s sialidases.fasta 
Traceback (most recent call last):
  File "/home/abbottlab/anaconda3/envs/saccharis/bin/saccharis", line 10, in <module>
    sys.exit(cli_main())
             ^^^^^^^^^^
  File "/home/abbottlab/anaconda3/envs/saccharis/lib/python3.11/site-packages/saccharis/CLI.py", line 232, in cli_main
    raise Exception("Error parsing user sequence file(s) from command line. This shouldn't happen, "
Exception: Error parsing user sequence file(s) from command line. This shouldn't happen, please report as a bug through github.

**Comment by lowkri** [comment]
While we are waiting for a solution to the most recent version, please install an older version that should work in the meantime.
'conda install saccharis=2.0.0.dev21'
